### ISSUE TITLE
Error to compil

### ISSUE THREAD

**Issue by wefgame** [lohvht/mod-random-suffix#1]
"When trying to compile this modification on a clean AzerothCore core of the latest revision, it produces a compilation error: "", but there are no errors with the random enchant mod."

Severity Code Description Project File Line Suppression State
Error LNK2019 unresolved external symbol "void cdecl Addmod_random_suffixScripts(void)" (?Addmod_random_suffixScripts@@YAXXZ) referenced in function "void cdecl AddModulesScripts(void)" (?AddModulesScripts@@YAXXZ). worldserver C:\server\Start\src\server\apps\modules.lib(ModulesLoader.obj) 1

**Comment by wefgame** [comment]
![image](https://user-images.githubusercontent.com/127363221/226249884-54551221-6f34-452f-8f4a-746089052eb6.png)
![image](https://user-images.githubusercontent.com/127363221/226249917-a08fc0c5-d08e-4a93-b0f9-b29e57ca7a3f.png)
![image](https://user-images.githubusercontent.com/127363221/226249965-9eb67073-69b3-4b53-80c9-6fc3f7ab1fc2.png)
![image](https://user-images.githubusercontent.com/127363221/226249988-f5e70baa-e386-4595-b763-2bee58163915.png)


CMake version: 3.26.0
Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
The CXX compiler identification is MSVC 19.35.32215.0
The C compiler identification is MSVC 19.35.32215.0
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
Detecting CXX compile features
Detecting CXX compile features - done
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe - skipped
Detecting C compile features
Detecting C compile features - done
> Warning: module using deprecated add config file api
-- Solo LFG CONFIGURED --
Running cmake hook: AFTER_LOAD_CONF
No hooks registered for AFTER_LOAD_CONF
Enabled С++20 standard
Detected 64-bit platform
MSVC: Minimum version required is 19.24, found 19.35.32215.0 - ok!
MSVC: 64-bit platform, enforced -D_WIN64 parameter
MSVC: Enabled extended object-support for debug-compiles
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Disabled INTMAX_MAX warnings
MSVC: Enable NOMINMAX
MSVC: Disabled generic compiletime warnings
Using installation path for configuration files
Running cmake hook: AFTER_LOAD_CMAKE_MODULES
No hooks registered for AFTER_LOAD_CMAKE_MODULES
Found MySQL library: C:/Program Files/MySQL/MySQL Server 8.0/lib/libmysql.lib
Found MySQL headers: C:/Program Files/MySQL/MySQL Server 8.0/include
Found MySQL executable: C:/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe
Found git binary : C:/Program Files/Git/cmd/git.exe

* AzerothCore revision            : a1dd4e162591+ 2023-03-15 21:30:49 +0000 (master branch)

* Install core to                 : C:/Program Files (x86)/AzerothCore
* Install configs to              : C:/Program Files (x86)/AzerothCore

* Build applications              : Yes (all)
* Build tools                     : No
* Build with scripts              : Yes (static)
* Build with modules              : Yes (static)
* Build unit tests                : No  (default)
* Build core w/PCH                : Yes (default)
* Build scripts w/PCH             : Yes (default)
* Show compile-warnings           : No  (default)
* Use coreside debug              : No  (default)
* Use MySQL sourcetree            : No
* Use GIT revision hash           : Yes (default)
* Enable vmap DisableMgr checks   : Yes (default)
* Show source tree                : Yes - "hierarchical"

Found Boost: C:/boost_1_81_0 (found suitable version "1.81.0", minimum required is "1.74") found components: system filesystem program_options iostreams regex 
Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM
Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM - Success
Looking for _strtod_l
Looking for _strtod_l - found
Found OpenSSL: optimized;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MD.lib;debug;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MDd.lib (found version "1.1.1t") found components: Crypto SSL 
Found OpenSSL library: optimized;C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MD.lib;debug;C:/Program Files/OpenSSL-Win64/lib/VC/libssl64MDd.lib;optimized;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MD.lib;debug;C:/Program Files/OpenSSL-Win64/lib/VC/libcrypto64MDd.lib
Found OpenSSL headers: C:/Program Files/OpenSSL-Win64/include
Looking for C++ include filesystem
Looking for C++ include filesystem - found
Performing Test CXX_FILESYSTEM_NO_LINK_NEEDED
Performing Test CXX_FILESYSTEM_NO_LINK_NEEDED - Success
Performing Test CMAKE_HAVE_LIBC_PTHREAD
Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
Looking for pthread_create in pthreads
Looking for pthread_create in pthreads - not found
Looking for pthread_create in pthread
Looking for pthread_create in pthread - not found
Found Threads: TRUE  
Running cmake hook: BEFORE_SRC_LOAD
No hooks registered for BEFORE_SRC_LOAD

* Apps build list (all):
  |
  +- apps
  |   +- authserver
  |   +- worldserver
  |

Running cmake hook: BEFORE_GAME_LIBRARY
No hooks registered for BEFORE_GAME_LIBRARY
Running cmake hook: AFTER_GAME_LIBRARY
No hooks registered for AFTER_GAME_LIBRARY
Running cmake hook: BEFORE_SCRIPTS_LIBRARY
No hooks registered for BEFORE_SCRIPTS_LIBRARY
* Script configuration (static):
  |
  +- worldserver
  |   +- Commands
  |   +- Custom
  |   +- EasternKingdoms
  |   +- Events
  |   +- Kalimdor
  |   +- Northrend
  |   +- OutdoorPvP
  |   +- Outland
  |   +- Pet
  |   +- Spells
  |   +- World
  |

* Modules configuration (static):
  |
  +- worldserver
  |   +- BreakingNewsOverride
  |   +- DungeonRespawn
  |   +- ExtendedXP
  |   +- mod-anticheat
  |   +- mod-autobalance
  |   +- mod-eluna
  |   +- mod-learn-spells
  |   +- mod-npc-gambler
  |   +- mod-random-suffix
  |   +- mod-solo-lfg
  |   +- mod-transmog
  |   +- mod-weekend-xp
  |

> Module (mod-solo-lfg) using deprecated loader api
* Modules config list:
  |
  +- BreakingNewsOverride
  |  * breakingnews.conf.dist
  +- DungeonRespawn
  |  * dungeonrespawn.conf.dist
  +- ExtendedXP
  |  * extendedxp.conf.dist
  +- mod-anticheat
  |  * Anticheat.conf.dist
  +- mod-autobalance
  |  * AutoBalance.conf.dist
  +- mod-eluna
  |  * mod_LuaEngine.conf.dist
  +- mod-learn-spells
  |  * mod_learnspells.conf.dist
  +- mod-npc-gambler
  |  * npc_gambler.conf.dist
  +- mod-random-suffix
  |  * RandomEnchants.conf.dist
  +- mod-solo-lfg
  |  * SoloLfg.conf.dist
  +- mod-transmog
  |  * transmog.conf.dist
  +- mod-weekend-xp
  |  * mod-double-xp-weekend.conf.dist

Running cmake hook: AFTER_SRC_LOAD
No hooks registered for AFTER_SRC_LOAD
Configuring done (35.9s)

**Comment by wefgame** [comment]
Очистка начата…
1>------ Очистка начата: проект: ALL_BUILD, Конфигурация: RelWithDebInfo x64 ------
2>------ Очистка начата: проект: worldserver, Конфигурация: RelWithDebInfo x64 ------
3>------ Очистка начата: проект: scripts, Конфигурация: RelWithDebInfo x64 ------
4>------ Очистка начата: проект: modules, Конфигурация: RelWithDebInfo x64 ------
5>------ Очистка начата: проект: gsoap, Конфигурация: RelWithDebInfo x64 ------
6>------ Очистка начата: проект: game, Конфигурация: RelWithDebInfo x64 ------
7>------ Очистка начата: проект: authserver, Конфигурация: RelWithDebInfo x64 ------
8>------ Очистка начата: проект: shared, Конфигурация: RelWithDebInfo x64 ------
9>------ Очистка начата: проект: database, Конфигурация: RelWithDebInfo x64 ------
10>------ Очистка начата: проект: common, Конфигурация: RelWithDebInfo x64 ------
11>------ Очистка начата: проект: sfmt, Конфигурация: RelWithDebInfo x64 ------
12>------ Очистка начата: проект: g3dlib, Конфигурация: RelWithDebInfo x64 ------
13>------ Очистка начата: проект: fmt, Конфигурация: RelWithDebInfo x64 ------
14>------ Очистка начата: проект: argon2, Конфигурация: RelWithDebInfo x64 ------
15>------ Очистка начата: проект: Detour, Конфигурация: RelWithDebInfo x64 ------
16>------ Очистка начата: проект: revision.h, Конфигурация: RelWithDebInfo x64 ------
17>------ Очистка начата: проект: Recast, Конфигурация: RelWithDebInfo x64 ------
18>------ Очистка начата: проект: zlib, Конфигурация: RelWithDebInfo x64 ------
19>------ Очистка начата: проект: ZERO_CHECK, Конфигурация: RelWithDebInfo x64 ------
========== Очистка: успешно — 19, неудачно — 0, пропущено — 0 ==========
========== Очистить запущено в 9:55 AM, заняло 04,868 с ==========

**Comment by wefgame** [comment]
As soon as the kernel is assembled, I will send the kernel collection log

**Comment by wefgame** [comment]
Severity Code Description Project File Line Suppression State
Error LNK2019 unresolved external symbol "void cdecl Addmod_random_suffixScripts(void)" (?Addmod_random_suffixScripts@@YAXXZ) referenced in function "void cdecl AddModulesScripts(void)" (?AddModulesScripts@@YAXXZ). worldserver C:\server\Start\src\server\apps\modules.lib(ModulesLoader.obj) 1

**Comment by wefgame** [comment]
Dear developers, I solved this problem, specify a very important thing in the installation information so that newcomers to the subtype do not come across this: After entering the command, the Gitbash console cannot be closed until the kernel is compiled, thanks and sorry for the messages.

**Comment by lohvht** [comment]
Hi! Thanks getting back to me @wefgame. Could i double check with you again that you're now able to compile Azerothcore successfully? If so I will go ahead and close this issue.

Thanks!

**Comment by wefgame** [comment]
Yes compile done!

**Comment by lohvht** [comment]
Thanks for confirming! Will be closing this issue for now.
