### ISSUE TITLE
[Question] Suffix stats formula calculation

### ISSUE THREAD

**Issue by wefgame** [lohvht/mod-random-suffix#2]
![image](https://user-images.githubusercontent.com/127363221/227116694-47c2781f-9229-4f48-8326-f6fd9ae2f2d4.png)
Dear developer, please tell me how the formula for stats is calculated, and is there a base for id stats by type of strength, agility, endurance, crit, etc.? ♥

**Comment by wefgame** [comment]
♥

**Comment by lohvht** [comment]
Hi! This module relies on the core's stat calculation algorithm. So the formula for stat calculation is pretty much the same as how the core will handle for normal items with suffixes.

Stats are generally dependent on the item's ItemLevel, item subtype and their respective allocation pct for the given suffix. Only the last (i.e.allocation pct)  is directly controlled via this module, using the clientside patch-Z.mpq folder, as well as the SQL overrides.

The core first calculates the item's suffix factor (lets call this `f`) via the item's itemlevel, quality and subtype (to be more precise, this suffix factor is determined by entries in `RandPropPoints.dbc`), the relevant part of the core's code is at this [link](https://github.com/azerothcore/azerothcore-wotlk/blob/967f8ce6d66b5378fc307d4f7f3ca3a40c1f55b0/src/server/game/Entities/Item/ItemEnchantmentMgr.cpp#L122).

The stats are calculated then by this formula (relevant code in core [here](https://github.com/azerothcore/azerothcore-wotlk/blob/edb9df9347a14454341bbf2be6fd13be8d9fe4b4/src/server/game/Entities/Player/PlayerStorage.cpp#L4411))
```
stats = f * AllocationPct_N / 10000
```

The base stats for custom suffixes can be changed if you edit the `generatesuffixes.conf.yaml` and change the `stat-point-alloc-tiers` values and then regenerate the DBC + SQL files. The steps are in the README file [here](https://github.com/lohvht/mod-random-suffix#advanced-usage), but these can only change the proportion of stats.

**Comment by lohvht** [comment]
For example

Lets say I get an Epic itemlevel 258 2H Weapon with the suffix `[Strength I]`, using the default AllocationPct `10000` as defined in the generated SQL in `sql/data/db-world/mod_acore_random_suffix.sql`. 2H weapons have suffixfactor=0 based on the code [here](https://github.com/azerothcore/azerothcore-wotlk/blob/967f8ce6d66b5378fc307d4f7f3ca3a40c1f55b0/src/server/game/Entities/Item/ItemEnchantmentMgr.cpp#L151)

Using the `RandPropPoints.dbc` values here (https://wow.tools/dbc/?dbc=randproppoints&build=3.3.5.12340#page=1&colFilter[0]=258), the value for `f` for 2H weapons at ilvl 258 (see `Epic[0]` column) is `291`, so the strength stat calculation will be as follows

```
stats = f * AllocationPct_N  / 10000 = 291 * 10000 / 10000 = 291
```

So for the above example, `[Strength I]` gives 291 strength for a ilvl 258 Epic 2H weapon.

**Comment by wefgame** [comment]
Thank you for such a quick response and such detailed information! The problem now is only with the display of ru RU elements, which is exactly what we are doing. So far, it is not possible to defeat dbc in Russian ♥

**Comment by lohvht** [comment]
This is a tough one because I mainly play on a enUS client haha. I wouldn't mind accepting a PR for this

**Comment by lohvht** [comment]
I'll go ahead and close this issue first as there seems to be no further action other than the additional feature request, which I have noted down here: https://github.com/lohvht/mod-random-suffix/issues/3

Thanks!
