### ISSUE TITLE
Always displayed 0 on legendary items

### ISSUE THREAD

**Issue by Knoot** [lohvht/mod-random-suffix#4]
**Describe the bug**
Stat values for legendary items are not displayed

**To Reproduce**
.additem 48750 - correct
.additem 49623 - incorrect

**Expected behavior**
Displaying stat values of suffixes

**Screenshots**
![1](https://user-images.githubusercontent.com/20779211/227722969-4787a720-9fba-43b3-8563-555c0f9ca492.png)
![2](https://user-images.githubusercontent.com/20779211/227723409-3619ef49-118f-4d27-81c1-2973d09a06b3.png)
![3](https://user-images.githubusercontent.com/20779211/227723568-d133a946-9235-4f7d-a3d7-e9822a0c701e.png)

**Desktop (please complete the following information):**
 - ubuntu 20.04 (WSL2)

**Additional context**
It is noticed that lowering the quality level to epic (5 -> 4) fixes the problem.
When comparing items, the difference in characteristics (including suffixes) is displayed

**Comment by wefgame** [comment]
confirm the problem, exactly the same situation

**Comment by lohvht** [comment]
Hi! Thanks for writing in. I confirmed the behaviour above is expected.

Legendary items on the WoW 3.3.5 client are not supposed to have suffixes, thus when displaying on client side, the client will render the stats as 0. But the [azerothcore server patch](https://github.com/lohvht/mod-random-suffix/blob/feat/mod-random-suffix/acore-modrandomsuffix.patch) that this module provides takes care of the correct stat calculation such that stats will always take effect.

As you can see from the picture you linked earlier
![image](https://user-images.githubusercontent.com/20779211/227723409-3619ef49-118f-4d27-81c1-2973d09a06b3.png)

Even though stats show as 0, the comparison on the left shows the proper values, i,e, `808 Intellect`. And i also believe that if you equip the item on your char, you should also get the stats.

I'm not so sure if its possible to get this fixed without extensive changes for the WoW client.

**Comment by Knoot** [comment]
thx
